apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-explorer
  template:
    metadata:
      labels:
        app: file-explorer
    spec:
      containers:
      - name: file-explorer
        image: file-explorer:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: file-explorer-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: file-explorer
